Home@feat
WildCodeSchool-2024-02/JS-RMT-Julien-StreetArtHunter-P3 pull request #19
Opened 2024-08-07 14:23 UTC by Megane45

2024-08-07 14:29 UTC, JohnnyDomingues approved these changes

2024-08-07 14:32 UTC, MariaKSanz approved these changes

2024-08-07 14:48 UTC, jujuck requested changes

2024-08-07 14:48 UTC, jujuck commented on client/src/main.jsx
>          element: <Home />,
element: `<Enter />`

2024-08-07 14:48 UTC, jujuck commented on client/src/main.jsx
> +        element: <Enter />,
path: "street-arts"
element: `<Home />`
 loader: () =>
          connexion
            .get("api/streetarts")
            .then((response) => response.data)
            .catch((error) => {
              console.error(
                "Erreur lors de la récupération des données de StreetArt:",
                error
              );
              return [];
            }),

2024-08-07 15:07 UTC, NicolasFollain submitted a review, later dismissed

2024-08-07 15:10 UTC, NessaGi submitted a review, later dismissed

2024-08-08 06:54 UTC, jujuck requested changes

2024-08-08 06:54 UTC, jujuck commented on client/src/pages/Enter.jsx
> +    <div>
Mettre directement le contenu de ton composant. HomeEnter. HomeEnter ne sera pas réutilisé en l'état dans une autre page, donc ce n'est pas un composant.... Fusionne les 2 directement dans la page

2024-08-08 07:20 UTC, JohnnyDomingues submitted a review, later dismissed

2024-08-08 07:21 UTC, MariaKSanz approved these changes

2024-08-08 07:54 UTC, jujuck requested changes

2024-08-08 07:54 UTC, jujuck commented on client/src/pages/Enter.jsx
> +    <div className="App-header-enter">
Balise main peut être. C'est la partie principale de ton site... On place une balise div qu'en dernier recours

2024-08-08 07:54 UTC, jujuck commented on client/src/pages/Enter.jsx
> +      <div className="content">
Balise section,

2024-08-08 07:54 UTC, jujuck commented on client/src/pages/Enter.jsx
> +      <div className="about-section">
Idem, balise section

2024-08-08 09:04 UTC, NessaGi approved these changes

2024-08-08 09:04 UTC, AnnDo33 approved these changes

2024-08-08 09:11 UTC, AnnDo33 approved these changes

2024-08-08 09:11 UTC, NessaGi approved these changes

2024-08-08 11:55 UTC, jujuck approved these changes

2024-08-08 11:55 UTC, merged