Detail@feat
WildCodeSchool-2024-02/JS-RMT-Julien-StreetArtHunter-P3 pull request #31
Opened 2024-08-20 14:53 UTC by NessaGi

2024-08-20 20:07 UTC, Megane45 approved these changes

2024-08-21 08:27 UTC, AnnDo33 submitted a review, later dismissed

2024-08-21 08:27 UTC, JohnnyDomingues approved these changes

2024-08-21 08:27 UTC, Megane45 submitted a review, later dismissed

2024-08-21 08:33 UTC, kpeset requested changes

2024-08-21 08:33 UTC, kpeset commented on client/src/components/Geolocation.jsx
> +            <a href={`/street-art-detail/${streetArt.id}`} style={{ textDecoration: 'none', color: 'inherit' }}>
Est-ce qu'il n'y a pas mieux à faire qu'une balise a ? :)

2024-08-21 10:22 UTC, NessaGi commented on client/src/components/Geolocation.jsx
> +            <a href={`/street-art-detail/${streetArt.id}`} style={{ textDecoration: 'none', color: 'inherit' }}>
Non, il n'y a pas mieux à faire selon moi :)

2024-08-21 12:19 UTC, Megane45 approved these changes

2024-08-21 13:23 UTC, kpeset approved these changes

2024-08-21 13:35 UTC, NicolasFollain approved these changes

2024-08-21 13:37 UTC, merged