Gallery@page
WildCodeSchool-2024-02/JS-RMT-Julien-StreetArtHunter-P3 pull request #35
Opened 2024-08-29 15:24 UTC by JohnnyDomingues

2024-08-29 21:17 UTC, Megane45 approved these changes

2024-08-30 07:23 UTC, NessaGi submitted a review, later dismissed

2024-08-30 07:23 UTC, NicolasFollain submitted a review, later dismissed

2024-08-30 07:40 UTC, jujuck requested changes

2024-08-30 07:40 UTC, jujuck commented on client/src/pages/Gallery.jsx
> +          <div
Mise en place d'un composant

2024-08-30 07:40 UTC, jujuck commented on client/src/pages/Gallery.jsx
> +  const handleCardClick = (id) => {
Mettre la logique de navigation dans le composant

2024-08-30 07:53 UTC, Megane45 approved these changes

2024-08-30 08:38 UTC, jujuck submitted a review, later dismissed

2024-08-30 08:41 UTC, merged