configuration de multer dans le server
WildCodeSchool-2024-02/JS-RMT-Julien-StreetArtHunter-P3 pull request #45
Opened 2024-09-02 13:50 UTC by JohnnyDomingues

2024-09-02 14:42 UTC, MariaKSanz approved these changes

2024-09-02 14:46 UTC, Megane45 approved these changes

2024-09-03 06:59 UTC, jujuck requested changes
Suppression des images uploadé et fin du front

2024-09-03 08:27 UTC, Megane45 submitted a review, later dismissed

2024-09-03 08:27 UTC, AnnDo33 submitted a review, later dismissed

2024-09-03 08:57 UTC, jujuck requested changes

2024-09-03 08:57 UTC, jujuck commented on server/app/controllers/streetartActions.js
> +const updateStreetarts = async (req, res, next) => {
Je crois que cela ne sert à rien. A retirer

2024-09-03 09:20 UTC, jujuck approved these changes

2024-09-03 09:20 UTC, merged