Début Config style css
WildCodeSchool-2024-02/JS-RMT-Julien-StreetArtHunter-P3 pull request #5
Opened 2024-07-11 09:43 UTC by AnnDo33

2024-07-11 09:57 UTC, Megane45 approved these changes

2024-07-11 09:58 UTC, NessaGi approved these changes

2024-07-11 10:23 UTC, jujuck requested changes

2024-07-11 10:23 UTC, jujuck commented on client/src/styles/btn-enter.css
> +@import url("https://www.dafont.com/fr/retrotech.font");
Cette partie serait mieux dans le fichier App.css. 
*, body, html

2024-07-11 10:23 UTC, jujuck commented on client/src/styles/btn-login-out.css
> +body {
Idem, uniformisation de vos bodys

2024-07-11 14:30 UTC, Megane45 approved these changes

2024-07-11 14:30 UTC, MariaKSanz submitted a review, later dismissed

2024-07-12 08:12 UTC, Megane45 approved these changes

2024-07-12 08:12 UTC, JohnnyDomingues approved these changes

2024-07-12 08:30 UTC, jujuck requested changes

2024-07-12 08:30 UTC, jujuck commented on client/src/styles/BtnEnter.css
> +:root {
Remplacer par une className

2024-07-12 09:03 UTC, MariaKSanz approved these changes

2024-07-12 09:05 UTC, Megane45 approved these changes

2024-07-12 09:05 UTC, NessaGi approved these changes

2024-07-12 09:11 UTC, jujuck approved these changes

2024-07-12 09:11 UTC, merged