Users@route
WildCodeSchool-2024-02/JS-RMT-Julien-StreetArtHunter-P3 pull request #7
Opened 2024-07-11 14:21 UTC by JohnnyDomingues

2024-07-11 14:22 UTC, Megane45 approved these changes

2024-07-11 14:22 UTC, MariaKSanz approved these changes

2024-07-12 08:21 UTC, MariaKSanz approved these changes

2024-07-12 08:23 UTC, Megane45 submitted a review, later dismissed

2024-07-12 08:42 UTC, jujuck requested changes
plus finir le css

2024-07-12 08:42 UTC, jujuck commented on client/src/components/User.jsx
> +    axios
Importe la connexion et utilise la à la place d'axios

2024-07-12 08:42 UTC, jujuck commented on client/src/main.jsx
> +    path: "/user",
route plutôt /administration/users

2024-07-12 08:42 UTC, jujuck commented on server/app/router.js
>  // Route to get a list of items
Modifie le commentaire items => users

2024-07-12 08:42 UTC, jujuck commented on server/database/models/UserRepository.js
> +  async create(user) {
Comment la méthode car elle n'est pas utilisée

2024-07-12 08:42 UTC, jujuck commented on server/database/models/UserRepository.js
> +  async read(id) {
Commente la méthode car elle n'est pas utilisée

2024-07-12 13:02 UTC, NessaGi submitted a review, later dismissed

2024-07-12 13:03 UTC, MariaKSanz submitted a review, later dismissed

2024-07-12 13:05 UTC, Megane45 approved these changes

2024-07-12 13:16 UTC, Megane45 approved these changes

2024-07-12 13:17 UTC, Megane45 submitted a review, later dismissed

2024-07-12 13:18 UTC, NessaGi submitted a review, later dismissed

2024-07-12 13:39 UTC, Megane45 approved these changes

2024-07-12 13:39 UTC, NessaGi submitted a review, later dismissed

2024-07-12 13:40 UTC, Megane45 submitted a review, later dismissed
good

2024-07-12 13:52 UTC, jujuck submitted a review, later dismissed

2024-07-12 13:52 UTC, jujuck commented on client/src/main.jsx
> +
Attention, ligne vide

2024-07-12 13:53 UTC, jujuck approved these changes

2024-07-12 13:54 UTC, Megane45 approved these changes

2024-07-12 13:54 UTC, AnnDo33 approved these changes

2024-07-12 13:54 UTC, MariaKSanz approved these changes

2024-07-12 13:54 UTC, merged